/*
  Cryson

  Copyright 2011-2012 Björn Sperber (cryson@sperber.se)

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

/*
 * Jakefile
 * Cryson Client Framework
*/

var ENV = require("system").env,
    FILE = require("file"),
    OS = require("os"),
    JAKE = require("jake"),
    task = JAKE.task,
    CLEAN = require("jake/clean").CLEAN,
    FileList = JAKE.FileList,
    framework = require("cappuccino/jake").framework,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Release";

framework ("Cryson", function(task)
{
    task.setBuildIntermediatesPath(FILE.join("Build", "Cryson.build", configuration));
    task.setBuildPath(FILE.join("Build", configuration));

    task.setProductName("Cryson");
    task.setIdentifier("se.sperber.Cryson");
    task.setVersion("0.6.12");
    task.setAuthor("Björn Sperber");
    task.setEmail("cryson @nospam@ sperber.se");
    task.setSummary("Cryson");
    task.setSources(new FileList("Cryson/*.j"));
    task.setResources(new FileList("Cryson/Resources/**/**"));
    task.setInfoPlistPath("Cryson/Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task("build", ["Cryson"]);

task("debug", function()
{
    ENV["CONFIG"] = "Debug"
    JAKE.subjake(["."], "build", ENV);
});

task("release", function()
{
    ENV["CONFIG"] = "Release"
    JAKE.subjake(["."], "build", ENV);
});

task ("documentation", function()
{
   OS.system("doxygen Doxyfile")
});


task("test", function()
{
    var tests = new FileList('Test/*Test.j');
    var cmd = ["ojtest"].concat(tests.items());
    var cmdString = cmd.map(OS.enquote).join(" ");

    var code = OS.system(cmdString);
    if (code !== 0)
        OS.exit(code);
});

task ("default", ["release"]);
task ("docs", ["documentation"]);
task ("all", ["release", "debug", "documentation"]);
